// v116: Wi-Fi-транспорт ext-gps.js (сообщения Durable Object → точки/события) — node hardware/pitlane-gps/test/wifi.test.mjs
import assert from 'node:assert/strict';
globalThis.navigator ??= { userAgent: 'node', maxTouchPoints: 0 };
globalThis.document ??= { visibilityState: 'visible', addEventListener() {}, removeEventListener() {} };
const m = await import('../../../ext-gps.js');
const pts = []; const evs = []; const states = [];
let sock = null; let opens = 0;
const g = m.createExtGps({ onPoint: (p) => pts.push(p), onEvent: (e) => evs.push(e), onState: (s) => states.push(s) });
g.connectWifi({ open: async () => { opens++; sock = { readyState: 1, sent: [], send(x) { this.sent.push(JSON.parse(x)); }, close() { this.readyState = 3; } }; return sock; } });
await new Promise((r) => setTimeout(r, 10));
assert.equal(g.state(), 'wifi'); assert.ok(g.active()); assert.equal(opens, 1);
sock.onopen();
assert.equal(sock.sent[0].type, 'ping', 'ping сразу после открытия (RTT для задержки)');
const now = Date.now();
const msg = (o) => sock.onmessage({ data: JSON.stringify(o) });
msg({ type: 'hello', s: now, dev: { on: true, devId: 'gabc12345', name: 'PITLANE-GPS-1A2B' }, status: { hz: 25, bat: 3950, pct: 71 } });
msg({ type: 'pong', c: now - 80, s: now });
let info = g.info();
assert.equal(info.wifi.chipOn, true); assert.equal(info.name, 'PITLANE-GPS-1A2B'); assert.equal(info.status.battPct, 71); assert.equal(info.status.rateHz, 25);
const row = (dt, v, fix = 11) => [dt, 555716000 + dt, 381419000, v, 120, 12, 13, fix];
const t0 = now - 300;
msg({ type: 'pts', bid: 'b1', q: 0, t0, s: now - 100, p: [row(0, 0), row(40, 50), row(80, 120)] });
assert.equal(pts.length, 3);
assert.equal(pts[0].timestamp, t0); assert.equal(pts[2].timestamp, t0 + 80, 'время точки — UTC чипа, не время прихода');
assert.ok(Math.abs(pts[2].coords.speed - 1.2) < 1e-9); assert.equal(pts[2].coords.ext, true); assert.equal(pts[2].ext.source, 'wifi');
assert.ok(Math.abs(pts[2].coords.accuracy - 1.2) < 1e-9);
msg({ type: 'pts', bid: 'b1', q: 1, t0: t0 + 40, s: now, p: [row(0, 50), row(40, 120), row(80, 200)] });
assert.equal(pts.length, 4, 'повтор уже принятых точек отброшен (идемпотентно)');
assert.equal(pts[3].timestamp, t0 + 120);
msg({ type: 'pts', bid: 'b1', q: 4, t0: t0 + 160, s: now, p: [row(0, 250, 0)] });
assert.equal(pts.length, 4, 'точка без фикса в пайплайн не идёт');
assert.ok(g.info().wifi.lagMs >= 0 && g.info().wifi.lagMs < 2000, 'задержка оценена: ' + g.info().wifi.lagMs);
msg({ type: 'ev', bid: 'b1', id: 1, e: 'mark', k: '0-100', ms: 3412, at: now - 200, s: now - 150 });
msg({ type: 'ev', bid: 'b1', id: 1, e: 'mark', k: '0-100', ms: 3412, at: now - 200, s: now - 150 });
assert.equal(evs.length, 1, 'событие — один раз');
assert.equal(evs[0].k, '0-100'); assert.ok(evs[0].lagMs >= 50 && evs[0].lagMs < 200, 'lag события ' + evs[0].lagMs); assert.ok(evs[0].ageMs < 1000);
msg({ type: 'ev', bid: 'b1', id: 2, e: 'end', at: now - 60000, s: now - 59900, marks: { '0-100': 3412 } });
assert.ok(evs[1].ageMs > 50000, 'старое событие (повтор при подключении) помечено возрастом');
msg({ type: 'pts', bid: 'b2', q: 0, t0: now, s: now, p: [row(0, 0)] });
assert.equal(pts.length, 5, 'новый запуск чипа (bid) — нумерация с нуля');
msg({ type: 'dev', on: false });
assert.equal(g.info().wifi.chipOn, false);
// обрыв сокета → переподключение
sock.readyState = 3; sock.onclose();
assert.equal(g.info().wifi.link, 'down');
await new Promise((r) => setTimeout(r, 900));
assert.equal(opens, 2, 'переподключение после обрыва');
g.disconnect();
assert.equal(g.state(), 'off'); assert.ok(!g.active());
console.log('wifi.test OK');
process.exit(0);
