// v124: нижняя панель из трёх пунктов (Дуэли · Paddock · Трассы) → шторка в стиле Telegram — node test/v124.test.mjs
import fs from 'fs';
let fails = 0; const ok = (c, m) => { if (c) console.log('  ✓', m); else { fails++; console.log('  ✗', m); } };
const root = new URL('../../', import.meta.url).pathname;
const html = fs.readFileSync(root + 'index.html', 'utf8'); const css = fs.readFileSync(root + 'styles.css', 'utf8');
const app = fs.readFileSync(root + 'app.js', 'utf8'); const sw = fs.readFileSync(root + 'sw.js', 'utf8');
console.log('[панель]');
const bar = html.slice(html.indexOf('<nav class="tabbar" id="tabbar">'), html.indexOf('</nav>', html.indexOf('id="tabbar"')));
const tabs = [...bar.matchAll(/class="nav-btn sheet-tab" data-sheet="([a-z]+)"/g)].map((m) => m[1]);
ok(tabs.join(',') === 'duels,pulse,tracks', 'ровно три пункта: Дуэли, Paddock, Трассы');
ok(/id="tabPill"/.test(bar) && /\.tab-pill \{[\s\S]{0,400}transition: transform \.38s cubic-bezier/.test(css), 'та же «пилюля» с пружинным переездом');
ok(/\.nav-btn:active \{ transform: scale\(\.92\); \}/.test(css) && /\.nav-btn\.active \.ico-lap \{ animation: icoPop/.test(css), 'сжатие при нажатии и анимация иконки как у старых вкладок');
ok(/html\.nav-widgets \.rail nav\.tabbar > \.nav-btn\.sheet-tab \{ display: flex; \}/.test(css) && /^\.nav-btn\.sheet-tab \{ display: none; \}/m.test(css), 'пункты-шторки только на телефоне; десктопный рейл без изменений');
ok(/html\.nav-widgets main \{ padding-bottom: calc\(96px \+ var\(--sab, 0px\)\); \}/.test(css), 'Главная с отступом под панель и safe-area');
ok(/!activeBtn\.getClientRects\(\)\.length\) \{ pill\.style\.opacity = '0'/.test(app), 'пилюля прячется, когда шторка закрыта');
console.log('[шторка]');
ok(/id="tgSheet" role="dialog" aria-modal="true"/.test(html) && /class="tgs-grab"/.test(html) && /id="tgSheetScrim"/.test(html), 'диалог с граббером и затемнением');
ok(/border-radius: 22px 22px 0 0/.test(css) && /\.tgs\.on \.tgs-panel \{ transform: translate3d\(0, 0, 0\); \}/.test(css), 'выезжает снизу, скруглённый верх');
ok(/html\.tgs-open #viewHost \{ transform: scale\(\.94\)/.test(css), 'лёгкое уменьшение фона');
const tgsCss = css.slice(css.indexOf('/* ——— v124: шторка'));
ok(!/transition:[^;]*\b(top|height|bottom|left|margin)\b/.test(tgsCss), 'анимации только transform/opacity');
ok(/@media \(prefers-reduced-motion: reduce\) \{\s*\.tgs-panel, \.tgs-scrim/.test(css), 'prefers-reduced-motion');
ok(/\['tgSheet', 'tgSheetClose'\],\n  \];/.test(app), 'BackButton Telegram закрывает шторку (после листов, открытых поверх)');
ok(/getElementById\('tgSheetScrim'\)\?\.addEventListener\('click', \(\) => closeTgSheet\(\)\)/.test(app) && /e\.key === 'Escape' && TGS\.open\) closeTgSheet\(\)/.test(app), 'закрытие тапом по фону и Esc');
ok(/fromHead \|\| body\.scrollTop <= 0/.test(app) && /\{ passive: false \}/.test(app) && /dy > 120 \|\| \(v > 0\.55 && dy > 40\)/.test(app), 'свайп вниз: шапка — всегда, контент — только с верха; порог/скорость');
ok(/if \(TGS\.open === kind\) \{ closeTgSheet\(\); return; \}/.test(app) && /panel\.classList\.add\('swap'\); tgsFill\(kind\)/.test(app), 'переключение пунктов без закрытия; повторный тап закрывает');
ok(/tgsPark\(v, body\)/.test(app) && /function tgsRestore\(\)/.test(app), 'разделы переносятся в шторку и возвращаются (обработчики сохраняются)');
ok(/if \(typeof TGS !== 'undefined' && TGS\.open\) closeTgSheet\(\{ instant: true \}\)/.test(app), 'переход на любой вид закрывает шторку');
ok(!/vibrate|HapticFeedback\.(impact|notification)Occurred\(/.test(app.slice(app.indexOf('/* ——— v124: нижняя панель'), app.indexOf('/* v120: главная кнопка'))), 'без вибрации');
console.log('[бейджи]');
ok(/duelCategory\(d\) === 'inbox'\)\.length/.test(app) && /Number\(p\.at\) > seen/.test(app), 'реальные счётчики: входящие вызовы, новые посты с последнего просмотра');
ok(/b\.textContent = n > 9 \? '9\+' : String\(n \|\| ''\)/.test(app), 'бейдж через textContent');
console.log('[версия]');
ok(/const APP_VERSION = 'v1(2[4-9]|[3-9]\d)'/.test(app) && /pitlane-v1(2[4-9]|[3-9]\d)/.test(sw), 'APP_VERSION / SW ≥ v124');
ok(/script-src 'self'/.test(html) && !/script-src[^;]*unsafe-inline/.test(html), 'CSP не ослаблен');
console.log(fails ? `\n${fails} FAIL` : '\nOK'); process.exit(fails ? 1 : 0);
