// v127: премиальная чистка — токены, один акцент, шрифт цифр (самохост OFL), без эмодзи/прочерков, аватарки-миниатюры — node test/v127.test.mjs
import rawWorker from '../src/index.js';
import { withAutoRefresh } from './autorefresh.mjs';
import { MemKV } from './kvmock.mjs';
import fs from 'fs';
const worker = withAutoRefresh(rawWorker);
let fails = 0; const ok = (c, m, x) => { if (c) console.log('  ✓', m); else { fails++; console.log('  ✗', m, x ?? ''); } };
const root = new URL('../../', import.meta.url).pathname;
const html = fs.readFileSync(root + 'index.html', 'utf8'); const css = fs.readFileSync(root + 'styles.css', 'utf8');
const app = fs.readFileSync(root + 'app.js', 'utf8'); const sw = fs.readFileSync(root + 'sw.js', 'utf8');
console.log('[шрифт цифр]');
for (const w of [500, 600]) { const f = root + `fonts/inter-display-num-${w}.woff2`; ok(fs.existsSync(f) && fs.readFileSync(f).toString('ascii', 0, 4) === 'wOF2' && fs.statSync(f).size < 12000, `самохост woff2 ${w} (< 12 КБ)`); }
ok(fs.existsSync(root + 'fonts/Inter-OFL.txt') && /SIL OPEN FONT LICENSE/i.test(fs.readFileSync(root + 'fonts/Inter-OFL.txt', 'utf8')), 'лицензия OFL рядом со шрифтом');
ok(/@font-face \{ font-family: "PL Num"; src: url\("\.\/fonts\/inter-display-num-500\.woff2"\)/.test(css) && /unicode-range: U\+0020-003A/.test(css), '@font-face c unicode-range (только цифры)');
ok(!/Barlow Condensed|Oswald/.test(css) && !/Barlow\+Condensed|Oswald/.test(html), 'Barlow/Oswald убраны — один шрифт для цифр');
ok(/body \{ font-variant-numeric: tabular-nums; \}/.test(css), 'tabular-nums');
ok(/font-src 'self' data: https:\/\/fonts\.gstatic\.com;/.test(html) && /script-src 'self'/.test(html), 'CSP не менялся');
ok(/inter-display-num-500\.woff2/.test(sw), 'шрифт в precache SW');
console.log('[токены и акцент]');
for (const t of ['--c-acc', '--r-lg', '--sp-4', '--sh-1', '--font-num', '--c-line']) ok(css.includes(t + ':'), 'токен ' + t);
ok(/\.nav-badge \{ background: var\(--c-text\) !important/.test(css) && /\.pc-bh b, \.hw-who \{ color: var\(--c-text\)/.test(css) && /\.tb-row\.me \{ background: var\(--c-surface-2\)/.test(css), 'бейджи/ники/моя строка — без зелёного');
ok(/\.hw-k, #hwCarSub, \.eyebrow[^{]*\{\s*text-transform: none !important/.test(css), 'меньше разряженного капса');
console.log('[без эмодзи и прочерков]');
ok(!/[\u2600-\u27BF\u2B50\u{1F300}-\u{1FAFF}]/u.test(app.replace(/'☰'|☰/g, '')), 'в app.js нет эмодзи/символов-бейджей');
ok(!/content: ' ⚔'|content: "★ "/.test(css), 'в CSS нет ⚔/★');
ok(/'tb-car', shortCarName\(r\.car, r\.carId\) \|\| ''\)/.test(app) && /<strong id="hdrLap"><\/strong>/.test(html) && /<span id="gpsAcc"><\/span>/.test(html), 'пустые значения — без «—»');
console.log('[аватарки]');
ok(/function padAvaUrl\(pilotId, ava\)/.test(app) && /--ava-h/.test(app) && /radial-gradient\(120% 120% at 28% 18%, hsl\(var\(--ava-h/.test(css), 'монограмма на графите + миниатюра по версии');
const kv = new MemKV(); const env = { PITLANE: kv, SMS_DEMO: '1' }; let ip = 1;
const call = async (m, p, { body, token } = {}) => { const h = { Origin: 'https://dsssssz.github.io', 'Content-Type': 'application/json', 'CF-Connecting-IP': '10.127.0.' + (ip++) }; if (token) h.Authorization = 'Bearer ' + token; const r = await worker.fetch(new Request('https://api.test' + p, { method: m, headers: h, body: body ? JSON.stringify(body) : undefined }), env); const buf = new Uint8Array(await r.arrayBuffer()); let d = null; try { d = JSON.parse(new TextDecoder().decode(buf)); } catch (_) {} return { status: r.status, h: r.headers, buf, d }; };
const o = await call('POST', '/auth/otp', { body: { phone: '79001270001' } }); const v = (await call('POST', '/auth/verify', { body: { phone: '79001270001', code: o.d.demoCode, nick: 'Artem' } })).d;
const o2 = await call('POST', '/auth/otp', { body: { phone: '79001270002' } }); const v2 = (await call('POST', '/auth/verify', { body: { phone: '79001270002', code: o2.d.demoCode, nick: 'Liza' } })).d;
const png = 'data:image/png;base64,' + Buffer.from([137, 80, 78, 71, 13, 10, 26, 10, 1, 2, 3]).toString('base64');
await kv.put('pilotmeta:' + v.pilotId, JSON.stringify({ avatar: png }));
await call('POST', '/pulse', { token: v.token, body: { text: 'с фото' } }); await call('POST', '/pulse', { token: v2.token, body: { text: 'без фото' } });
const feed = (await call('GET', '/pulse?recent=1')).d;
const withP = feed.find((p) => p.text === 'с фото'); const noP = feed.find((p) => p.text === 'без фото');
ok(/^[a-z0-9]{2,16}$/.test(withP.ava || '') && !('ava' in noP), 'в ленте — только короткая версия, без самой картинки', JSON.stringify(withP));
ok(!JSON.stringify(feed).includes('base64'), 'аватарки не встраиваются в JSON ленты');
const a = await call('GET', `/pilot/${v.pilotId}/avatar?v=${withP.ava}`);
ok(a.status === 200 && a.h.get('content-type') === 'image/png' && /max-age=86400/.test(a.h.get('cache-control')) && a.h.get('x-content-type-options') === 'nosniff' && a.buf[0] === 137, 'GET /pilot/:id/avatar — байты, кэшируемо, nosniff');
ok((await call('GET', `/pilot/${v2.pilotId}/avatar`)).status === 404 && (await call('GET', '/pilot/../avatar')).status === 404, 'нет фото / неверный id — 404');
await kv.put('pilotmeta:' + v2.pilotId, JSON.stringify({ avatar: 'https://evil.example/track.png' }));
ok((await call('GET', `/pilot/${v2.pilotId}/avatar`)).status === 404, 'чужие хосты не проксируются (только Telegram CDN)');
await kv.put('pilotmeta:' + v2.pilotId, JSON.stringify({ avatar: 'https://t.me/i/userpic/320/x.jpg' }));
const tg = await call('GET', `/pilot/${v2.pilotId}/avatar`); ok(tg.status === 302 && tg.h.get('location') === 'https://t.me/i/userpic/320/x.jpg', 'Telegram CDN — редирект');
console.log('[версия]');
ok(/const APP_VERSION = 'v1(2[7-9]|[3-9]\d)'/.test(app) && /pitlane-v1(2[7-9]|[3-9]\d)/.test(sw), 'APP_VERSION / SW ≥ v127');
console.log(fails ? `\n${fails} FAIL` : '\nOK'); process.exit(fails ? 1 : 0);
